# ワークフロー名
name: Delete workflow runs

# トリガー
on:
  # 手動で実行する
  workflow_dispatch:

# ジョブ
jobs:
  delete-runs:
    # 実行環境
    runs-on: ubuntu-latest
    # ステップ
    steps:
      # GitHub CLIのインストール
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      # ワークフロー実行履歴の削除
      - name: Delete workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHubのアクセストークン（Secretsから取得）
        run: |
          # リポジトリ名とワークフロー名を動的に取得（環境変数やコンテキストから取得）
          owner="${{ github.repository_owner }}"
          repo="${{ github.repository }}"
          file_name="${{ github.workflow }}"

          # ワークフロー実行履歴のIDを取得して削除するコマンドを生成
          gh api "repos/$owner/$repo/actions/workflows/$file_name/runs?per_page=100" \
          | jq -r '.workflow_runs[].id' \
          | xargs -I{} echo "gh api repos/$owner/$repo/actions/runs/{} -X DELETE" > delete.sh

          # コマンドを実行してワークフロー実行履歴を削除
          bash delete.sh
